### ISSUE TITLE
add command item in Docker-compose file

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-memcached#3]
e.g m is max_cache, c is max_connect_thread
```
    version: '3.8'
    services:
    memcached:
        image: memcached:${APP_VERSION}
        container_name: ${APP_CONTAINER_NAME}
        restart: always
        command:
        - '-m 2048'
        - '-c 2048'
```
